# Generated by Django 4.1.4 on 2023-02-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyexpense',
            name='daily_expenses',
            field=models.FloatField(default=0.0),
        ),
    ]
